import os
import re
import json
import hashlib
import logging
from email import message_from_string
from datetime import datetime
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from openai import OpenAI
from dotenv import load_dotenv
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse

load_dotenv()
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="PhishGuard API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)
app.mount("/static", StaticFiles(directory="static"), name="static")

@app.get("/")
async def serve_frontend():
    return FileResponse("static/index.html")

class EmailRequest(BaseModel):
    email_text: str
    mode: str = "user"  # "user" or "analyst"

class ReportRequest(BaseModel):
    analysis: dict
    reporter_name: str = "Anonymous"

def extract_metadata(raw_email: str) -> dict:
    msg = message_from_string(raw_email)
    urls = re.findall(r'https?://[^\s<>"]+', raw_email)
    from_addr = msg.get("From", "")
    reply_to = msg.get("Reply-To", "")
    from_domain = from_addr.split("@")[-1].strip(">") if "@" in from_addr else ""
    reply_domain = reply_to.split("@")[-1].strip(">") if "@" in reply_to else None
    return {
        "from": from_addr,
        "reply_to": reply_to,
        "subject": msg.get("Subject", ""),
        "domain_mismatch": reply_domain != from_domain if reply_domain else False,
        "urls_found": urls
    }

def call_codex(email_text: str, metadata: dict, mode: str) -> dict:
    mode_instruction = (
        "Use plain, non-technical language suitable for any user."
        if mode == "user"
        else "Use technical security terminology. Include MITRE ATT&CK techniques if applicable. List all IOCs."
    )
    prompt = f"""
You are a cybersecurity analyst specializing in phishing detection.
{mode_instruction}

Pre-extracted metadata:
{json.dumps(metadata, indent=2)}

Full email:
{email_text}

Return ONLY valid JSON with this exact structure:
{{
  "risk_level": "HIGH" | "MEDIUM" | "LOW",
  "confidence": 0-100,
  "verdict": "one sentence summary",
  "highlighted_phrases": [
    {{"text": "exact phrase from email", "reason": "why suspicious"}}
  ],
  "indicators": [
    {{"text": "description", "reason": "explanation", "severity": "HIGH|MEDIUM|LOW"}}
  ],
  "recommended_actions": ["action 1", "action 2"],
  "analyst_notes": "technical detail for security analysts"
}}

No markdown. No preamble. JSON only.
"""
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=1000
    )
    return json.loads(response.choices[0].message.content)

@app.post("/analyze")
async def analyze(request: EmailRequest):
    if not request.email_text.strip():
        raise HTTPException(status_code=400, detail="Email text is required")
    
    # Privacy: log only hash, never the full email
    email_hash = hashlib.sha256(request.email_text.encode()).hexdigest()[:8]
    logger.info({"event": "analysis_requested", "hash": email_hash, "mode": request.mode})
    
    metadata = extract_metadata(request.email_text)
    result = call_codex(request.email_text, metadata, request.mode)
    result["metadata"] = metadata
    return result

@app.post("/report")
async def generate_report(request: ReportRequest):
    a = request.analysis
    indicators = "\n".join(
        f"- {i['text']}: {i['reason']}" 
        for i in a.get("indicators", [])
    )
    report = f"""PHISHING REPORT — {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}
Submitted by: {request.reporter_name}
Risk Level: {a.get('risk_level', 'UNKNOWN')}
Confidence: {a.get('confidence', 0)}%
Verdict: {a.get('verdict', '')}

From: {a.get('metadata', {}).get('from', 'N/A')}
Subject: {a.get('metadata', {}).get('subject', 'N/A')}
URLs found: {', '.join(a.get('metadata', {}).get('urls_found', [])) or 'None'}

Indicators:
{indicators}

Recommended Actions:
{chr(10).join('- ' + action for action in a.get('recommended_actions', []))}

Generated by PhishGuard"""
    return {"report": report}

@app.get("/examples")
async def get_examples():
    return {"examples": [
        {
            "label": "PayPal Phishing",
            "email": """From: security@paypa1-support.ru\nReply-To: harvester@evil.com\nSubject: Urgent: Your account will be suspended in 24 hours\n\nDear Customer,\nYour PayPal account has been flagged. Click here immediately to verify:\nhttp://paypa1-verify.ru/login\nFailure to act will result in permanent suspension."""
        },
        {
            "label": "Bank Spear Phish",
            "email": """From: alerts@bankofamerica-secure.net\nSubject: Unusual login detected on your account\n\nDear valued customer,\nWe detected a login from an unrecognized device in Moscow, Russia.\nPlease confirm your identity within 2 hours or your account will be locked.\nhttps://boa-verify-identity.net/confirm"""
        },
        {
            "label": "IT Help Desk Impersonation",
            "email": """From: helpdesk@company-support.co\nSubject: Your password expires today\n\nHi,\nYour corporate password expires in 2 hours. Reset it immediately:\nhttp://reset-corp-password.xyz/portal\nIT Support Team"""
        }
    ]}

@app.get("/health")
async def health():
    return {"status": "ok"}